Repository HKN-UCSD/hkn-member-portal, pull requests merged in 2020-07, with the labels that each got.

#87 Removed the redundant MajorDropdown and YearDropdown folders.
  src/components/dropdowns/MajorDropdown/index.js
  src/components/dropdowns/YearDropdown/index.js
Labels: refactor

#101 Added CustomTextField and exposed name and label props for dropdowns.
  src/components/InputField/index.js
  src/components/dropdowns/MajorDropdownField/index.js
  src/components/dropdowns/YearDropdownField/index.js
  src/components/dropdowns/index.js
Labels: dev experience, enhancement

#105 Added 'lint_prettier' job, which is made from 'lint' job.
  .circleci/config.yml
Labels: dev experience, low priority

#106 Added endpoints.js to store endpoint constants for API fetch calls.
  src/constants/endpoints.js
Labels: dev experience

#109 Added BaseModal, ConfirmModal and AlertModal.
  src/components/DeleteEditButtons/index.js
  src/components/buttons/index.js
  src/components/modals/base/BaseModal.js
  src/components/modals/base/ButtonWithModal.js
  src/components/modals/index.js
Labels: enhancement, feature

#108 ProfilePage + Edit
  src/components/FormLayout/index.js
  src/components/FormLayout/styles.js
  src/components/InputField/index.js
  src/components/NavBar/tabs.js
  src/components/formSections/AccountSection.js
  src/components/formSections/PersonalInfoSection.js
  src/components/formSections/index.js
  src/constants/routes.js
  src/pages/App/index.js
  src/pages/ProfileEditPage/index.js
  src/pages/ProfileEditPage/schema.js
  src/pages/ProfileEditPage/styles.js
  src/pages/ProfilePage/index.js
  src/pages/ProfilePage/styles.js
Labels: feature

#112 Navigating to invalid enpoints now redirects to the home page.
  src/pages/App/index.js
Labels: bug
