Repository HKN-UCSD/hkn-member-portal, pull requests merged in 2020-06, with the labels that each got.

#52 CircleCi Project Setup
  .circleci/config.yml
  .eslintrc
  package.json
Labels: dev experience

#53 Adds stuff to run cypress tests
  .circleci/config.yml
  cypress.json
  cypress/integration/critical_path.spec.js
  cypress/integration/examples/actions.spec.js
  cypress/integration/examples/aliasing.spec.js
  cypress/integration/examples/assertions.spec.js
  cypress/integration/examples/connectors.spec.js
  cypress/integration/examples/cookies.spec.js
  cypress/integration/examples/cypress_api.spec.js
  cypress/integration/examples/files.spec.js
  cypress/integration/examples/local_storage.spec.js
  cypress/integration/examples/location.spec.js
  cypress/integration/examples/misc.spec.js
  cypress/integration/examples/navigation.spec.js
  cypress/integration/examples/network_requests.spec.js
  cypress/integration/examples/querying.spec.js
  cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/integration/examples/traversal.spec.js
  cypress/integration/examples/utilities.spec.js
  cypress/integration/examples/viewport.spec.js
  cypress/integration/examples/waiting.spec.js
  cypress/integration/examples/window.spec.js
  cypress/plugins/index.js
  cypress/support/index.js
  package.json
Labels: dev experience

#81 Added sort by DateTime to the List view of Calendar.
  src/components/EventList/index.js
Labels: enhancement

#82 Added major and year dropdowns to use with forms made with Formik.
  src/components/dropdowns/MajorDropdown/index.js
  src/components/dropdowns/YearDropdown/index.js
  src/components/dropdowns/index.js
  src/constants/eligibleMajors.js
Labels: enhancement, feature

#86 Modified both dropdowns so that they allow props to bubble down.
  src/components/dropdowns/MajorDropdownField/index.js
  src/components/dropdowns/MajorDropdownField/styles.js
  src/components/dropdowns/YearDropdownField/index.js
  src/components/dropdowns/YearDropdownField/styles.js
  src/components/dropdowns/index.js
Labels: enhancement, feature
